### ISSUE TITLE
Criar controller para visualizar manutenção

### ISSUE THREAD

**Issue by rodrigondec** [rodrigondec/Open_Clineng#20]
- [x] controller _**detalhar_manutencao**_
retorna os detalhes da manutenção.
- [x] view

**Comment by Mazuh** [comment]
Implementação iniciada neste commit da branch issue/20
https://github.com/rodrigondec/Open_Clineng/commit/5a207ddd78abff895e6f87a7a25134a2b07539b7

Não dei nem PR nem nada porque não vi instruções de como gerar o banco de dados. Tentei rodar o comando de migração via manage.py mas só foram as tabelas padrões do Django, nada relativo ao Open_Clieng propriamente dito.

**Comment by rodrigondec** [comment]
É só o makemigrations é depois migrate. Mas se tiver usando o banco do config.py nem precisa pq ele já está configurado e é no server la. Só se alterar algum model
