### ISSUE TITLE
Criar template Base

### ISSUE THREAD

**Issue by rodrigondec** [rodrigondec/Open_Clineng#21]
- [x] bootstrap
recomendo utilizar um tema free do [bootswatch](https://bootswatch.com/3/). Recomendo usar o [CDN](https://www.bootstrapcdn.com/bootswatch/) deles
- [x] Navbar
com os menus Home, Equipamentos, Manutenções e Locais
- [x] footer

**Comment by Mazuh** [comment]
Tema: https://bootswatch.com/3/spacelab/
(A licença é MIT, devemos dar crédito ao moço, mas não sei onde fazer isso. EDIT: Coloquei no rodapé, mas não sei se dei os créditos à pessoa certa, nunca usei o bootswatch)

**Comment by rodrigondec** [comment]
https://en.wikipedia.org/wiki/MIT_License
Mit pelo que to vendo é quase uma GPL. Então ta de boa
